# Generated by Django 4.2.23 on 2025-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
