# Generated by Django 4.2.23 on 2025-09-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_pedido_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pix_chave',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pix_qr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefone_cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(),
        ),
    ]
