# Generated by Django 4.2.23 on 2025-09-28 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0005_categoria_icone_alter_categoria_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='icone',
        ),
        migrations.AddField(
            model_name='produto',
            name='curtido_por',
            field=models.ManyToManyField(blank=True, related_name='produtos_curtidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
